# Generated by Django 3.2.6 on 2021-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('available_pieces', models.PositiveIntegerField()),
            ],
        ),
    ]
