# Generated by Django 3.2.6 on 2021-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('cancel', 'cancel'), ('intransit', 'intransit'), ('ordered', 'ordered')], default='ordered', max_length=20),
        ),
    ]
