# Generated by Django 3.2.6 on 2021-09-08 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2021, 9, 13), null=True),
        ),
    ]
