# Generated by Django 3.2.6 on 2021-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='available_pieces',
            field=models.IntegerField(),
        ),
    ]
